-- status: reserved
-- owner: workforce
-- scope: Employment lifecycle and period-scoped UserId + OrganizationAccountId work relationship.
-- canonical target: docs/010-domain-owners/040-workforce.md
-- migration gate: docs/090-governance/030-migrations/040-enterprise-organization-workforce-payroll.md#workforce--attendance--payroll-implementation-slices
-- activation: remove reserved status only with current authority, participation/overlap policy, replay/version contract, data-topology relations, tests, and validation evidence.
