-- status: reserved
-- owner: workforce
-- scope: published Schedule and ScheduledDay planned work/rest facts.
-- canonical target: docs/010-domain-owners/040-workforce.md
-- migration gate: docs/090-governance/040-gaps/060-workforce.md
-- activation: remove reserved status only after schedule publication/version, authorization, and consumer contracts are current and tested.
