-- status: reserved
-- owner: payroll
-- scope: explicit PayPeriod identity used by PayrollRun and PayStatement lifecycle.
-- canonical target: docs/010-domain-owners/060-payroll.md
-- migration gate: docs/090-governance/040-gaps/090-payroll.md
-- activation: remove reserved status only after pay period validation, organization scope, authorization, data-topology relations, tests, and validation evidence are current.
