-- status: reserved
-- owner: audit
-- scope: immutable AuditEvent preservation for activated high-impact operations.
-- canonical target: docs/090-governance/020-proposals/040-security-target.md
-- migration gate: docs/090-governance/040-gaps/020-admin-workspace.md
-- activation: remove reserved status only when an Audit capability has a current consumer, minimum evidence fields, retention policy, data-topology relations, tests, and validation evidence.
